apiVersion: v1
kind: ConfigMap
metadata:
  name: federated-router-config
  namespace: federated-dp-llm
  labels:
    app: federated-router
    component: config
data:
  # Environment variables
  PYTHONPATH: "/app"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  REDIS_URL: "redis://redis-service:6379"
  PROMETHEUS_PORT: "8090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Feature flags
  ENABLE_PROMETHEUS_METRICS: "true"
  ENABLE_HEALTH_CHECKS: "true"
  ENABLE_REQUEST_LOGGING: "true"
  ENABLE_PRIVACY_AUDIT: "true"
  ENABLE_CONSENSUS_MODE: "true"
  
  # Performance settings
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_TIMEOUT: "30"
  POOL_MAX_SIZE: "20"
  POOL_MIN_SIZE: "5"
  
  # Privacy settings
  DEFAULT_EPSILON_PER_QUERY: "0.1"
  DEFAULT_DELTA: "1e-5"
  MAX_BUDGET_PER_USER: "10.0"
  PRIVACY_AUDIT_RETENTION_DAYS: "90"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: federated-router-config-files
  namespace: federated-dp-llm
  labels:
    app: federated-router
    component: config
data:
  production.yaml: |
    # Federated DP-LLM Production Configuration
    
    server:
      host: "0.0.0.0"
      port: 8080
      workers: 4
      reload: false
      access_log: true
      
    privacy:
      epsilon_per_query: 0.1
      delta: 1.0e-5
      max_budget_per_user: 10.0
      noise_multiplier: 1.1
      clipping_threshold: 1.0
      enable_audit: true
      audit_retention_days: 90
      
    security:
      jwt_secret_key: "${JWT_SECRET_KEY}"
      jwt_algorithm: "HS256"
      jwt_expiration_hours: 24
      enable_mtls: true
      ca_cert_path: "/app/certs/ca.crt"
      server_cert_path: "/app/certs/server.crt"
      server_key_path: "/app/certs/server.key"
      require_client_cert: true
      
    database:
      url: "${DATABASE_URL}"
      pool_size: 20
      max_overflow: 30
      pool_timeout: 30
      pool_recycle: 3600
      
    redis:
      url: "${REDIS_URL}"
      max_connections: 50
      socket_timeout: 5
      health_check_interval: 30
      
    monitoring:
      enable_prometheus: true
      prometheus_port: 8090
      enable_health_checks: true
      health_check_interval: 30
      log_level: "INFO"
      structured_logging: true
      
    caching:
      enable_memory_cache: true
      enable_redis_cache: true
      memory_cache:
        max_size: 1000
        default_ttl: 3600
      redis_cache:
        default_ttl: 7200
        prefix: "federated_dp:"
        
    performance:
      max_concurrent_requests: 100
      request_timeout: 30
      enable_connection_pooling: true
      connection_pool:
        min_size: 5
        max_size: 20
        max_idle_time: 300
        health_check_interval: 60
      enable_auto_scaling: true
      auto_scaling:
        min_instances: 2
        max_instances: 10
        scale_up_threshold: 0.8
        scale_down_threshold: 0.3
        
    federation:
      consensus_threshold: 0.8
      max_retries: 3
      retry_delay: 1.0
      node_timeout: 30
      health_check_interval: 60
      
    compliance:
      enable_hipaa_audit: true
      enable_gdpr_compliance: true
      data_retention_days: 90
      audit_log_encryption: true
      pii_detection: true
      department_budgets:
        emergency: 20.0
        cardiology: 15.0
        radiology: 10.0
        general: 5.0
        research: 2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: federated-dp-llm
  labels:
    app: federated-router
    component: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Path              /app/logs/*.log
        Parser            json
        Tag               federated.router
        Refresh_Interval  5
        Mem_Buf_Limit     50MB

    [INPUT]
        Name              tail
        Path              /app/logs/audit/*.log
        Parser            json
        Tag               federated.audit
        Refresh_Interval  5
        Mem_Buf_Limit     50MB

    [FILTER]
        Name                kubernetes
        Match               federated.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name  es
        Match federated.router
        Host  elasticsearch-service
        Port  9200
        Index federated-router-logs
        Type  _doc

    [OUTPUT]
        Name  es
        Match federated.audit
        Host  elasticsearch-service
        Port  9200
        Index federated-audit-logs
        Type  _doc

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: federated-dp-llm
  labels:
    app: redis
    component: cache
data:
  redis.conf: |
    # Redis configuration for Federated DP-LLM
    
    # Network
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # General
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    
    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # Security
    requirepass ${REDIS_PASSWORD}
    
    # Limits
    maxclients 10000
    maxmemory 2gb
    maxmemory-policy allkeys-lru
    
    # Append Only File
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128